# Generated by Django 6.0.3 on 2026-03-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_details', '0006_rename_reviewed_status_to_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
