"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from email.utils import formataddr
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-iar3(z4@(tk=l8i0j)gu77whwr4a+2%lif8m+-%l+b(7m9ia5!",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "127.0.0.1,localhost")
for host in (
    "127.0.0.1",
    "localhost",
    "api",
    "microservice",
    "host.docker.internal",
    "insurance-api",
    "insurance-microservice",
):
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")
USE_X_FORWARDED_HOST = os.getenv("USE_X_FORWARDED_HOST", "False").lower() == "true"
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "False").lower() == "true"
SESSION_COOKIE_SECURE = (
    os.getenv("SESSION_COOKIE_SECURE", "False").lower() == "true"
)
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "False").lower() == "true"

if os.getenv("SECURE_PROXY_SSL_HEADER", "").lower() == "true":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "apps.job_details",
    "apps.media_library",
    "apps.kyc",
    "apps.property",
    "apps.users",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    # Required by Django admin; JWT is only used for API authentication.
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "mysql.connector.django",
        "NAME": os.getenv("DB_NAME", "insurance_claim_help"),
        "USER": os.getenv("DB_USER", "root"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "3306"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

mail_encryption = os.getenv("MAIL_ENCRYPTION", "").strip().lower()
mail_from_address = os.getenv("MAIL_FROM_ADDRESS", "").strip()
mail_from_name = os.getenv("MAIL_FROM_NAME", "").strip()

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST") or os.getenv("MAIL_HOST", "127.0.0.1")
EMAIL_PORT = int(os.getenv("EMAIL_PORT") or os.getenv("MAIL_PORT", "1025"))
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", default=mail_encryption == "tls")
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", default=mail_encryption == "ssl")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER") or os.getenv("MAIL_USERNAME", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD") or os.getenv(
    "MAIL_PASSWORD", ""
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "").strip() or (
    formataddr((mail_from_name, mail_from_address))
    if mail_from_name and mail_from_address
    else mail_from_address or "noreply@insurance-claim-help.local"
)
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "30"))
MICROSERVICE_API_BASE_URL = os.getenv(
    "MICROSERVICE_API_BASE_URL",
    "http://127.0.0.1:8080/api/",
)
MICROSERVICE_INTERNAL_API_BASE_URL = os.getenv(
    "MICROSERVICE_INTERNAL_API_BASE_URL",
    "",
).strip()
MICROSERVICE_FETCH_TIMEOUT_SECONDS = int(
    os.getenv("MICROSERVICE_FETCH_TIMEOUT_SECONDS", "60")
)
REPORT_DOWNLOAD_TIMEOUT_SECONDS = int(
    os.getenv("REPORT_DOWNLOAD_TIMEOUT_SECONDS", "60")
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

UNFOLD = {
    "SITE_TITLE": "Insurance Claim Help Admin",
    "SITE_HEADER": "Insurance Claim Help",
    "SITE_SUBHEADER": "Claims, properties, KYC, and reporting",
    "SITE_SYMBOL": "shield",
    "SITE_LOGO": lambda request: static("logo-admin-cropped.png"),
    "SITE_ICON": lambda request: static("logo-admin.png"),
    "STYLES": [
        lambda request: static("admin-unfold.css"),
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SITE_DROPDOWN": [
        {
            "icon": "home",
            "title": "Main site",
            "link": "http://127.0.0.1:3000/",
        },
    ],
    "COLORS": {
        "primary": {
            "50": "239 246 251",
            "100": "220 238 244",
            "200": "188 221 230",
            "300": "140 197 213",
            "400": "86 168 188",
            "500": "31 122 140",
            "600": "23 95 109",
            "700": "15 76 92",
            "800": "11 57 69",
            "900": "8 44 53",
            "950": "5 27 32",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Administration",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Users",
                        "icon": "group",
                        "link": reverse_lazy("admin:users_user_changelist"),
                    },
                    {
                        "title": "Roles",
                        "icon": "badge",
                        "link": reverse_lazy("admin:users_role_changelist"),
                    },
                    {
                        "title": "Properties",
                        "icon": "home_work",
                        "link": reverse_lazy("admin:property_property_changelist"),
                    },
                    {
                        "title": "KYC",
                        "icon": "verified_user",
                        "link": reverse_lazy("admin:kyc_kyc_changelist"),
                    },
                    {
                        "title": "Job Details",
                        "icon": "assignment",
                        "link": reverse_lazy("admin:job_details_jobdetail_changelist"),
                    },
                    {
                        "title": "Media Library",
                        "icon": "perm_media",
                        "link": reverse_lazy("admin:media_library_medialibrary_changelist"),
                    },
                ],
            },
        ],
    },
}


def _split_env_list(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


CORS_ALLOWED_ORIGINS = _split_env_list(
    os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000",
    )
)
