# Generated by Django 6.0.3 on 2026-03-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("under_review", "Under Review"),
                    ("accepted", "Accepted"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
