# Generated by Django 6.0.3 on 2026-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_alter_report_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="user",
        ),
        migrations.AddField(
            model_name="report",
            name="user_id",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
