# Generated by Django 6.0.3 on 2026-03-26 12:20

import django.db.models.deletion
from django.db import migrations, models


def copy_room_detail_from_repair_item(apps, schema_editor):
    Report = apps.get_model("report", "Report")

    for report in Report.objects.select_related("repair_item").all():
        if report.repair_item_id:
            report.room_detail_id = report.repair_item.room_detail_id
            report.save(update_fields=["room_detail"])


class Migration(migrations.Migration):

    dependencies = [
        ("room_details", "0002_roomdetail_mesh_path_roomdetail_nerf_output_path_and_more"),
        ("report", "0003_replace_user_fk_with_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="room_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="room_details.roomdetail",
            ),
        ),
        migrations.RunPython(
            copy_room_detail_from_repair_item,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="report",
            name="repair_item",
        ),
        migrations.RemoveField(
            model_name="report",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="report",
            name="room_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="room_details.roomdetail",
            ),
        ),
    ]
