# Generated by Django 6.0.3 on 2026-03-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medialibrary',
            new_name='media_libra_mediabl_cee72a_idx',
            old_name='media_libra_mediabl_6cfcdb_idx',
        ),
    ]
