# Generated by Django 6.0.3 on 2026-03-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='mesh_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomdetail',
            name='nerf_output_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomdetail',
            name='processing_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
