# Generated by Django 6.0.3 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_details", "0002_roomdetail_mesh_path_roomdetail_nerf_output_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomdetail",
            name="property_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
