from io import BytesIO
from pathlib import Path

from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


NAVY = colors.HexColor("#0B3A66")
NAVY_DARK = colors.HexColor("#082E52")
TEAL = colors.HexColor("#58D0A8")
SKY = colors.HexColor("#77C8FF")
GOLD = colors.HexColor("#FFC857")
PINK = colors.HexColor("#F58BC2")
LAVENDER = colors.HexColor("#A78BFA")
TEXT = colors.HexColor("#0F172A")
MUTED = colors.HexColor("#64748B")
WHITE = colors.white
BORDER = colors.HexColor("#D7E2EE")
PANEL = colors.HexColor("#F8FBFF")


def build_report_pdf(payload: dict) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=22,
        rightMargin=22,
        topMargin=22,
        bottomMargin=22,
        title=f"Damage and Expense Report {payload['room_id']}",
    )

    styles = _styles()
    story = []

    story.extend(_hero(payload, styles))
    story.append(Spacer(1, 8))
    story.append(_info_grid(payload, styles))
    story.append(Spacer(1, 8))
    story.append(_context_grid(payload, styles))
    story.append(Spacer(1, 8))

    story.append(
        _feature_band(
            title="Damage Assessment",
            body=_damage_body(payload, styles),
            accent=TEAL,
            styles=styles,
        )
    )
    story.append(Spacer(1, 6))

    story.append(
        _feature_band(
            title="Repair Items",
            body=_repair_body(payload, styles),
            accent=SKY,
            styles=styles,
        )
    )

    if payload["media"]:
        story.append(PageBreak())
        story.extend(_media_section(payload, styles))

    story.append(Spacer(1, 8))
    story.append(
        Paragraph(
            "Generated by Insurance Claim Help for internal claim review and repair estimation.",
            styles["Footer"],
        )
    )

    doc.build(story)
    return buffer.getvalue()


def _hero(payload: dict, styles):
    logo_path = Path(__file__).resolve().parent / "static" / "report" / "logo-lg.png"
    top = []

    if logo_path.exists():
        logo = _scaled_image(str(logo_path), max_width=2.8 * inch, max_height=0.9 * inch)
        logo_card = Table([[logo]], colWidths=[3.0 * inch])
        logo_card.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), WHITE),
                    ("BOX", (0, 0), (-1, -1), 0, colors.transparent),
                    ("LEFTPADDING", (0, 0), (-1, -1), 10),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ]
            )
        )
        top.append(logo_card)
    else:
        top.append(Paragraph("Insurance Claim Help", styles["HeroBrand"]))

    top.append(Spacer(1, 10))
    top.append(Paragraph("Report", styles["HeroEyebrow"]))
    top.append(Paragraph("Damage and Expense Report", styles["HeroTitle"]))
    top.append(
        Paragraph(
            "A simple overview of room damages, repair costs, and supporting claim media.",
            styles["HeroSubtitle"],
        )
    )

    hero = Table([[top]], colWidths=[7.05 * inch])
    hero.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), NAVY),
                ("BOX", (0, 0), (-1, -1), 0, colors.transparent),
                ("LEFTPADDING", (0, 0), (-1, -1), 24),
                ("RIGHTPADDING", (0, 0), (-1, -1), 24),
                ("TOPPADDING", (0, 0), (-1, -1), 22),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 20),
            ]
        )
    )
    return [hero]


def _info_grid(payload: dict, styles):
    data = [
        [
            _metric("Room", f"#{payload['room_id']}", styles),
            _metric("Reference", payload["reference_number"], styles),
        ],
        [
            _metric("Status", payload["report_status"], styles),
            _metric("Total Cost", _currency(payload["total_cost"]), styles),
        ],
        [
            _metric("Repair Items", str(payload["repair_item_count"]), styles),
            _metric("Estimated Completion", payload["estimated_completion_time"], styles),
        ],
    ]
    table = Table(data, colWidths=[3.525 * inch, 3.525 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), WHITE),
                ("BOX", (0, 0), (-1, -1), 1, BORDER),
                ("INNERGRID", (0, 0), (-1, -1), 1, BORDER),
                ("LEFTPADDING", (0, 0), (-1, -1), 20),
                ("RIGHTPADDING", (0, 0), (-1, -1), 20),
                ("TOPPADDING", (0, 0), (-1, -1), 18),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 18),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    return table


def _context_grid(payload: dict, styles):
    property_data = payload.get("property") or {}
    user_data = payload.get("user") or {}

    owner_name = (
        user_data.get("name")
        or user_data.get("full_name")
        or " ".join(
            part
            for part in [
                user_data.get("first_name"),
                user_data.get("middle_name"),
                user_data.get("last_name"),
            ]
            if part
        )
        or "Not available"
    )
    address = (
        property_data.get("address")
        or property_data.get("address_line")
        or user_data.get("address_line_1")
        or "Not available"
    )
    owner_role = user_data.get("role_name") or user_data.get("role") or "Not available"
    property_type = (
        property_data.get("property_type") or user_data.get("property_type") or "Not available"
    )
    postcode = property_data.get("postcode") or user_data.get("postcode") or "Not available"
    contact_number = user_data.get("contact_number") or "Not available"
    email = user_data.get("email") or "Not available"

    data = [
        [
            _detail_card(
                "Property Details",
                [
                    ("Property ID", _safe_value(payload.get("property_id"))),
                    ("Address", address),
                    ("Type", property_type),
                    ("Postcode", postcode),
                ],
                styles,
            ),
            _detail_card(
                "Homeowner Details",
                [
                    ("Name", owner_name),
                    ("Role", owner_role),
                    ("Email", email),
                    ("Contact", contact_number),
                ],
                styles,
            ),
        ]
    ]
    table = Table(data, colWidths=[3.525 * inch, 3.525 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0, colors.transparent),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    return table


def _feature_band(title: str, body, accent, styles):
    left = Table(
        [[Paragraph(_band_title_text(title), styles["BandTitle"])]],
        colWidths=[2.2 * inch],
    )
    left.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), accent),
                ("BOX", (0, 0), (-1, -1), 0, colors.transparent),
                ("LEFTPADDING", (0, 0), (-1, -1), 16),
                ("RIGHTPADDING", (0, 0), (-1, -1), 16),
                ("TOPPADDING", (0, 0), (-1, -1), 14),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )

    right = Table([[body]], colWidths=[4.85 * inch])
    right.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), NAVY),
                ("BOX", (0, 0), (-1, -1), 0, colors.transparent),
                ("LEFTPADDING", (0, 0), (-1, -1), 16),
                ("RIGHTPADDING", (0, 0), (-1, -1), 16),
                ("TOPPADDING", (0, 0), (-1, -1), 14),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )

    band = Table([[left, right]], colWidths=[2.2 * inch, 4.85 * inch])
    band.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0, colors.transparent),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    return KeepTogether([band])


def _damage_body(payload, styles):
    if not payload["damages"]:
        return Paragraph("No damages were found for this room.", styles["BandBody"])

    rows = [["Type", "Location", "Severity"]]
    for damage in payload["damages"]:
        rows.append(
            [
                str(damage.get("type", "Unspecified")),
                str(damage.get("location", "Unknown")),
                str(damage.get("severity", "unknown")).title(),
            ]
        )
    return _table_on_dark(rows, [2.1 * inch, 2.1 * inch, 0.85 * inch])


def _repair_body(payload, styles):
    if not payload["repair_items"]:
        return Paragraph("No repair items are currently associated with this room.", styles["BandBody"])

    rows = [["ID", "Material", "Quantity", "Cost"]]
    for item in payload["repair_items"]:
        rows.append(
            [
                str(item["id"]),
                str(item["material"]),
                str(item["quantity"]),
                _currency(item["cost"]),
            ]
        )
    return _table_on_dark(rows, [0.55 * inch, 2.75 * inch, 0.85 * inch, 0.9 * inch])


def _media_body(payload, styles):
    blocks = []
    for item in payload["media"]:
        parts = [
            Paragraph(f"Media #{item['id']}", styles["MediaTitle"]),
            Spacer(1, 6),
        ]
        if item.get("image_path"):
            parts.append(
                _framed_image(
                    item["image_path"],
                    max_width=4.55 * inch,
                    max_height=3.5 * inch,
                )
            )
        else:
            parts.append(Paragraph("Image preview unavailable.", styles["BandBody"]))
        card = Table([[parts]], colWidths=[4.65 * inch])
        card.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), WHITE),
                    ("BOX", (0, 0), (-1, -1), 0, colors.transparent),
                    ("LEFTPADDING", (0, 0), (-1, -1), 14),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 14),
                    ("TOPPADDING", (0, 0), (-1, -1), 14),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
                ]
            )
        )
        blocks.append(card)
        blocks.append(Spacer(1, 10))
    return KeepTogether(blocks[:-1] if blocks else [Paragraph("No media files are attached to this room.", styles["BandBody"])])


def _media_section(payload, styles):
    blocks = [
        Paragraph("MEDIA", styles["MediaSectionTitle"]),
        Spacer(1, 8),
    ]
    for index, item in enumerate(payload["media"], start=1):
        blocks.append(_media_card(item, styles))
        if index < len(payload["media"]):
            blocks.append(Spacer(1, 8))
    return blocks


def _media_card(item: dict, styles):
    content = [
        Paragraph(f"Media #{item['id']}", styles["MediaTitle"]),
        Spacer(1, 6),
    ]
    if item.get("image_path"):
        content.append(
            _framed_image(
                item["image_path"],
                max_width=6.15 * inch,
                max_height=4.45 * inch,
            )
        )
    else:
        content.append(Paragraph("Image preview unavailable.", styles["BandBody"]))

    card = Table([[content]], colWidths=[7.05 * inch])
    card.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), WHITE),
                ("BOX", (0, 0), (-1, -1), 1, BORDER),
                ("LEFTPADDING", (0, 0), (-1, -1), 16),
                ("RIGHTPADDING", (0, 0), (-1, -1), 16),
                ("TOPPADDING", (0, 0), (-1, -1), 14),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    return card


def _table_on_dark(rows, col_widths):
    table = Table(rows, colWidths=col_widths, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), NAVY_DARK),
                ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("TEXTCOLOR", (0, 1), (-1, -1), TEXT),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, PANEL]),
                ("BOX", (0, 0), (-1, -1), 0, colors.transparent),
                ("INNERGRID", (0, 0), (-1, -1), 0.75, BORDER),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )
    return table


def _metric(label: str, value: str, styles):
    return Paragraph(
        f'<font color="#7B8CA4"><b>{label.upper()}</b></font><br/><font color="#16324F"><b>{value}</b></font>',
        styles["Metric"],
    )


def _detail_card(title: str, rows: list[tuple[str, str]], styles):
    body = [Paragraph(title, styles["SectionCardTitle"]), Spacer(1, 8)]
    for label, value in rows:
        body.append(
            Paragraph(
                f'<font color="#7B8CA4"><b>{label.upper()}</b></font><br/><font color="#16324F">{_escape(value)}</font>',
                styles["CardBody"],
            )
        )
        body.append(Spacer(1, 6))

    table = Table([[body[:-1]]], colWidths=[3.4 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), WHITE),
                ("BOX", (0, 0), (-1, -1), 1, BORDER),
                ("LEFTPADDING", (0, 0), (-1, -1), 16),
                ("RIGHTPADDING", (0, 0), (-1, -1), 16),
                ("TOPPADDING", (0, 0), (-1, -1), 14),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    return table


def _band_title_text(title: str) -> str:
    mapping = {
        "Damage Assessment": "DAMAGE<br/>ASSESSMENT",
        "Repair Items": "REPAIR<br/>ITEMS",
    }
    return mapping.get(title, title.upper())


def _framed_image(path: str, max_width: float, max_height: float):
    image = _scaled_image(path, max_width=max_width, max_height=max_height)
    table = Table([[image]], colWidths=[max_width + 0.2 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), WHITE),
                ("BOX", (0, 0), (-1, -1), 1.2, BORDER),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ]
        )
    )
    return table


def _scaled_image(path: str, max_width: float, max_height: float):
    with PILImage.open(path) as img:
        width, height = img.size
    scale = min(max_width / width, max_height / height)
    return Image(path, width=width * scale, height=height * scale)


def _currency(value) -> str:
    try:
        return f"£{float(value):,.2f}"
    except (TypeError, ValueError):
        return str(value)


def _ownership_status(property_data: dict) -> str:
    if not any(
        key in property_data
        for key in ["ownership_verified", "ownership_rejected", "ownership_reject_reason"]
    ):
        return "Not available"
    if property_data.get("ownership_verified"):
        return "Verified"
    if property_data.get("ownership_rejected"):
        reason = property_data.get("ownership_reject_reason")
        return f"Rejected ({reason})" if reason else "Rejected"
    return "Pending"


def _safe_value(value) -> str:
    if value in (None, ""):
        return "Not available"
    return str(value)


def _escape(value) -> str:
    return (
        _safe_value(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _styles():
    styles = getSampleStyleSheet()
    styles.add(
        ParagraphStyle(
            name="HeroBrand",
            parent=styles["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=15,
            leading=18,
            textColor=WHITE,
        )
    )
    styles.add(
        ParagraphStyle(
            name="HeroEyebrow",
            parent=styles["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            alignment=TA_LEFT,
            textColor=colors.HexColor("#D6E8FF"),
        )
    )
    styles.add(
        ParagraphStyle(
            name="HeroTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=24,
            leading=28,
            alignment=TA_LEFT,
            textColor=WHITE,
        )
    )
    styles.add(
        ParagraphStyle(
            name="HeroSubtitle",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=11,
            leading=15,
            alignment=TA_LEFT,
            textColor=colors.HexColor("#D8E8F7"),
        )
    )
    styles.add(
        ParagraphStyle(
            name="Metric",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=11,
            leading=15,
            alignment=TA_LEFT,
            textColor=TEXT,
        )
    )
    styles.add(
        ParagraphStyle(
            name="BandTitle",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=17,
            alignment=TA_LEFT,
            textColor=NAVY_DARK,
        )
    )
    styles.add(
        ParagraphStyle(
            name="BandBody",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            alignment=TA_LEFT,
            textColor=WHITE,
        )
    )
    styles.add(
        ParagraphStyle(
            name="MediaTitle",
            parent=styles["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=14,
            alignment=TA_CENTER,
            textColor=TEXT,
        )
    )
    styles.add(
        ParagraphStyle(
            name="MediaSectionTitle",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=20,
            alignment=TA_LEFT,
            textColor=NAVY_DARK,
        )
    )
    styles.add(
        ParagraphStyle(
            name="Footer",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=8,
            leading=10,
            alignment=TA_CENTER,
            textColor=MUTED,
        )
    )
    styles.add(
        ParagraphStyle(
            name="SectionCardTitle",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            alignment=TA_LEFT,
            textColor=NAVY_DARK,
        )
    )
    styles.add(
        ParagraphStyle(
            name="CardBody",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            alignment=TA_LEFT,
            textColor=TEXT,
        )
    )
    return styles
